# 

trigger:
- dev

pool:
  vmImage: 'ubuntu-latest'

variables:
  location: "westeurope"
  rgName: "RG-azdevops-ARM-Stockage"

stages:
  - stage: Build
    displayName: 'Build Infra Stockage'
    jobs:
      - job: Build
        displayName: Build
        steps:
          - task: CopyFiles@2
            displayName: 'copy le script PS'
            inputs:
              SourceFolder: '$(Build.SourcesDirectory)'
              Contents: |
                **/rg.ps1
              TargetFolder: '$(build.artifactstagingdirectory)'
              condition: succeededOrFailed()

          - task: CopyPublishBuildArtifacts@1
            displayName: 'Publish artifacts'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'