# test

trigger:
- dev

pool:
  vmImage: 'windows-latest'

variables:
  location: "westeurope"
  rgName: "RG-azdevops-ARM-Stockage"

stages:
  - stage: Build
    displayName: 'Build Infra Stockage'
    jobs:
      - job: Build
        displayName: Build
        steps:
          - task: CopyFiles@2      
            displayName: 'copy fichier Powershell'
            inputs:
              SourceFolder: '$(Build.SourcesDirectory)'
              Contents: |
                **/rg.ps1
              TargetFolder: '$(build.artifactstagingdirectory)'
            condition: succeededOrFailed()
          
          - task: CopyFiles@2
            displayName: 'copy templates ARM'
            inputs:
              SourceFolder: '$(Build.SourcesDirectory)'
              Contents: |
                **/*.json
              TargetFolder: '$(build.artifactstagingdirectory)'
            condition: succeededOrFailed()

          - task: PublishBuildArtifacts@1
            displayName: 'Publish artifacts'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'
  
  - stage: Deployment
    displayName: 'Test Deployment'
    condition: succeeded()
    dependsOn: Build
    jobs:
      - deployment: Deployment
        pool:
          vmImage: 'windows-latest'
        environment: Dev
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzurePowerShell@5
                  inputs:
                    azureSubscription: 'Connexion-Abonnement-Azure'
                    ScriptPath: '$(Build.ArtifactStagingDirectory)\PowerShell\rg.ps1'
                    azurePowerShellVersion: 'LatestVersion'


