# 

trigger:
- dev

pool:
  vmImage: 'ubuntu-latest'

variables:
  location: "westeurope"
  rgName: "RG-azdevops-ARM-Stockage"

stages:
  - stage: Build
    displayName: 'Build Infra Stockage'
    jobs:
      - job: Build
        displayName: Build
        steps:
          - task: AzurePowerShell@5
            displayName: 'Creation du resource group'
            inputs:
              azureSubscription: 'Connexion-Abonnement-Azure'
              ScriptType: 'InlineScript'
              Inline: |
                $rg = Get-AzResourceGroup -name $(rgName) -location $(location)
                if($rg -eq $null)
                {
                  New-AzResourceGroup -name $(rgName) -location $(location)
                }
              azurePowerShellVersion: 'LatestVersion'
              errorActionPreference: 'silentlyContinue'