# Simple démo
trigger:
- dev

variables:
  location: 'westeurope'
  rgName: 'RG-azdevops-ARM-Stockage'

stages:
  - stage: Build
    displayName: 'Build Infra Stockage'
    jobs:
      - job: Build
        displayName: Build le Template ARM
        pool:
          vmImage: 'ubuntu-latest'
        steps:          
          - task: CopyFiles@2
            displayName: 'copy templates ARM'
            inputs:
              SourceFolder: '$(Build.SourcesDirectory)'
              Contents: |
                **/*.json
              TargetFolder: '$(build.artifactstagingdirectory)'
            condition: succeededOrFailed()

          - task: PublishBuildArtifacts@1
            displayName: 'Publish artifacts'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'
  
  - stage: Deployment
    displayName: 'Test de Deployment'
    condition: succeeded()
    dependsOn: Build
    jobs:
      - deployment: Deployment
        pool:
          vmImage: 'ubuntu-latest'
        environment: Dev
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzurePowerShell@5
                  inputs:
                    azureSubscription: 'Connexion-Abonnement-Azure'
                    ScriptType: 'InlineScript'
                    Inline: |
                      $rg = Get-AzResourceGroup -Name $(rgName) -location $(location)
                      if($rg -eq $null)
                      {
                        New-AzResourceGroup -name $(rgName) -location $(location)
                      }              
                    errorActionPreference: 'Continue'
                    azurePowerShellVersion: 'LatestVersion'

                - task: AzureResourceManagerTemplateDeployment@3
                  inputs:
                    deploymentScope: 'Resource Group'
                    azureResourceManagerConnection: 'Connexion-Abonnement-Azure'                    
                    action: 'Create Or Update Resource Group'
                    resourceGroupName: '$(rgName)'
                    location: '$(location)'
                    templateLocation: 'Linked artifact'
                    csmFile: '$(Pipeline.Workspace)/drop/ARM/azuredeploy.json'
                    csmParametersFile: '$(Pipeline.Workspace)/drop/ARM/azuredeploy.parameters.json'
                    deploymentMode: 'Incremental'                    